services:
  - type: web
    name: citation-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
